[package]
name = "rust-azure-ai-demos"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
reqwest = { version = "0", features = ["json"]}
serde_json = "1"
tokio = { version = "1", features = ["full"] }
